name: Sync Salt

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-salt:
    name: Fetch & Sync GoFile Salt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run GoFile Salt Sync
        run: node scraper/sync_salt.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status -s configs/gallery-dl.conf) ]]; then
            echo "Salt updated. Committing changes..."
            git add configs/gallery-dl.conf
            git commit -m "chore(gofile): salt updated [skip ci]"
            git push
          else
            echo "Salt is up-to-date. No changes to commit."
          fi
